# Data Preprocessing with Scikit-learn

This notebook covers the basic data preprocessing techniques used before training machine learning models.

## Topics

- Reading an Excel File
- Data Preprocessing
- Rescaling Data (Min-Max Scaling)
- Data Normalization
- Data Binarization (Convert to Binary)
- Data Standardization (Z-Score Scaling)
- Label Encoding
- Scikit-learn Basics
- Data Imputation
- Handling Missing Values
- Imputing Missing Values with the Mean
- Data Imputation Examples
- Exploratory Data Analysis (EDA)

## Goal

Learn how to clean, transform, and prepare data to improve machine learning model performance.

<details>
<summary> <strong>Machine Learning Workflow </strong></summary>

## 1. Data Preprocessing

Prepare and improve the data before training.

- Exploratory Data Analysis (EDA)
  - Explore and understand the dataset.
  - Find missing values, duplicates, outliers, and patterns.

- Feature Engineering
  - Create or transform features to improve the dataset.

- Feature Selection
  - Choose the most important features for the model.

---

## 2. Model Training

Build a machine learning model using a suitable algorithm.

- Train a classifier or regressor.
- Learn patterns from the training data.

---

## 3. Model Evaluation

Evaluate the model using performance metrics and test data.

---

## 4. Model Deployment

Deploy the trained model so users can access it through a website, application, or API.
</details>

In [1]:
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler,StandardScaler,Normalizer,Binarizer
from pandas import read_csv
from numpy import set_printoptions

path="pima-indians-diabetes.csv"
names=['preg','plas','pres','skin','test','mass','pedi','age','class']

# Data the inside file doesn't have columns names we assign column name to it using names attribute
dataframe=read_csv(path,names=names)
print(type(dataframe))
array=dataframe.values
print(type(array))
print(array.shape)



<class 'pandas.DataFrame'>
<class 'numpy.ndarray'>
(768, 9)


## Rows vs Columns in Preprocessing

### Normalizer
- Works on **rows (samples)**.
- Each **row is treated as one vector**.
- Scales each row so its **length (L2 norm) = 1**.

```text
Dataset

Height  Weight  Age
170      70      25   ← Vector (Row 1)
180      80      30   ← Vector (Row 2)
160      60      20   ← Vector (Row 3)
```

### Scalers (MinMaxScaler & StandardScaler)
- Work on **columns (features)**.
- Each feature is scaled independently.

```text
Height ↓
170
180
160

Weight ↓
70
80
60

Age ↓
25
30
20
```

### Easy Rule

- **Normalizer** → Normalize **Rows (Samples/Vectors)**.
- **MinMaxScaler** → Scale **Columns (Features)**.
- **StandardScaler** → Scale **Columns (Features)**.
- **Binarizer** → Converts each value independently to **0 or 1**.

## 1. Rescale Data (Min-Max Scaling)

- Scales all features to the same range (usually **0 to 1**).
- Improves the performance of many ML algorithms.
- Helps optimization algorithms like **Gradient Descent** converge faster.
- Important for algorithms sensitive to feature scale, such as:
  - Linear Regression
  - Neural Networks
  - K-Nearest Neighbors (KNN)

In [2]:

#feature_range() -> normalize each feature so there values are between 0 and 1

# fit() -> scaler learns from dataset and get min and max of each feature 
# transform() -> applies the formula of the MINMAX SCALER 
data_scaler=MinMaxScaler(feature_range=(0,1))
data_rescaled=data_scaler.fit_transform(array)

set_printoptions(precision=2)

print("Rescaled Data :\n",data_rescaled[:5])

Rescaled Data :
 [[0.35 0.74 0.59 0.35 0.   0.5  0.23 0.48 1.  ]
 [0.06 0.43 0.54 0.29 0.   0.4  0.12 0.17 0.  ]
 [0.47 0.92 0.52 0.   0.   0.35 0.25 0.18 1.  ]
 [0.06 0.45 0.54 0.23 0.11 0.42 0.04 0.   0.  ]
 [0.   0.69 0.33 0.35 0.2  0.64 0.94 0.2  1.  ]]


## 2. Normalization

- Scales each **row (sample)** to have a **length (norm) of 1**.
- Uses **L2 norm (Euclidean norm)** by default.
- Preserves the direction of the data.
- Different from Min-Max Scaling (0–1 scaling).
- Commonly used with KNN, clustering, and cosine similarity.

In [3]:

data_normalizer=Normalizer(norm='l2').fit_transform(array)
set_printoptions(precision=3)
print(data_normalizer)

[[0.034 0.828 0.403 ... 0.004 0.28  0.006]
 [0.008 0.716 0.556 ... 0.003 0.261 0.   ]
 [0.04  0.924 0.323 ... 0.003 0.162 0.005]
 ...
 [0.027 0.651 0.388 ... 0.001 0.161 0.   ]
 [0.007 0.838 0.399 ... 0.002 0.313 0.007]
 [0.008 0.736 0.554 ... 0.002 0.182 0.   ]]


## 3. StandardScaler (Z-Score Scaling)

- Scales **columns (features)**.
- Makes each feature have:
  - **Mean = 0**
  - **Standard Deviation = 1**
- Improves model performance and training speed.
- Commonly used with:
  - Linear Regression
  - Logistic Regression
  - SVM
  - Neural Networks

**Equation**

$$
x'=\frac{x-\mu}{\sigma}
$$

Where:
- $x$ = original value
- $\mu$ = mean of the feature
- $\sigma$ = standard deviation of the feature
```

In [4]:
data_scaler=StandardScaler().fit(array) # -> fit get mean and std
data_rescaled=data_scaler.transform(array)

set_printoptions(precision=2)

print("Rescaled Data :\n",data_rescaled[:5])

Rescaled Data :
 [[ 0.64  0.85  0.15  0.91 -0.69  0.2   0.47  1.43  1.37]
 [-0.84 -1.12 -0.16  0.53 -0.69 -0.68 -0.37 -0.19 -0.73]
 [ 1.23  1.94 -0.26 -1.29 -0.69 -1.1   0.6  -0.11  1.37]
 [-0.84 -1.   -0.16  0.15  0.12 -0.49 -0.92 -1.04 -0.73]
 [-1.14  0.5  -1.5   0.91  0.77  1.41  5.48 -0.02  1.37]]


## Binarizer

- Converts numerical values into **binary values (0 or 1)**.
- Compares each value with a **threshold**.
- Values **greater than the threshold** become **1**.
- Values **less than or equal to the threshold** become **0**.
- Commonly used for binary classification and feature preprocessing.

**Equation**

$$
x' =
\begin{cases}
1, & x > \text{threshold} \\
0, & x \le \text{threshold}
\end{cases}
$$

Where:
- $x$ = original value
- **threshold** = cutoff value (default is `0.0`)
```

In [5]:
binarizer=Binarizer(threshold=5)
data_binarized=binarizer.fit_transform(array)
print("Binarized Data : ",data_binarized )

Binarized Data :  [[1. 1. 1. ... 0. 1. 0.]
 [0. 1. 1. ... 0. 1. 0.]
 [1. 1. 1. ... 0. 1. 0.]
 ...
 [0. 1. 1. ... 0. 1. 0.]
 [0. 1. 1. ... 0. 1. 0.]
 [0. 1. 1. ... 0. 1. 0.]]


## Label Encoding

- Converts **categorical (text) values** into **numeric labels**.
- Each unique category is assigned a unique integer.
- Required because most machine learning algorithms work with numbers, not text.
- Used for **ordinal** or simple categorical features.


In [12]:

# input_labels=['r','b','g','r','b','y']
# encoder=preprocessing.LabelEncoder()
# encoded_values=encoder.fit_transform(input_labels)

# decoded_lst=encoder.inverse_transform(encoded_values)
# print("Labels : ",input_labels)
# print("Enoded Values : ",encoded_values)
# print(type(encoded_values))
# print("Decoded labels :",decoded_lst)


input_labels=['red','black','red','green','black','yellow','white']
encoder=preprocessing.LabelEncoder()
encoded_values=encoder.fit_transform(input_labels)

print("labels : ",input_labels)
print("Encoded Values : ",encoded_values)

decoded_values=encoder.inverse_transform(encoded_values)
print("Decoded Values  (must be like input labels ) :",decoded_values)



labels :  ['red', 'black', 'red', 'green', 'black', 'yellow', 'white']
Encoded Values :  [2 0 2 1 0 4 3]
Decoded Values  (must be like input labels ) : ['red' 'black' 'red' 'green' 'black' 'yellow' 'white']


## Data Imputation

- Replaces **missing values** with estimated values instead of deleting rows.
- Helps preserve the dataset and improve model performance.
- Common imputation methods applied on each **column**:
  - **Mean** (average) – for numerical data.
  - **Median** – for skewed numerical data.
  - **Mode** – for categorical data.

  - **Constant value** (e.g., 0 or "Unknown").


In [19]:
import numpy as np
from sklearn.impute import SimpleImputer

data=[[1,2,np.nan,3],[1,2,3,np.nan],[1,2,np.nan,3],[1,2,np.nan,3]]

data=np.array(data)
print("Original Data : \n",data)
print("="*50)

# i can define missing_values as i want 
imp_mean=SimpleImputer(missing_values=np.nan , strategy='mean')
imp_mean.fit(data)
modified_data=imp_mean.transform(data)
print("modified_data using mean strategy : \n",modified_data)

print("="*50)

data=[[1,2,np.nan],[3,np.nan,1],[5,np.nan,0],[np.nan,4,6],[5,0,np.nan],[4,5,5]]

imp_const=SimpleImputer(missing_values=np.nan , strategy='constant',fill_value=100)
modified_data=imp_const.fit_transform(data)
print("Origianl Data : \n",np.array(data))
print("="*50)
print("modified_data using constant strategy :\n",modified_data)

Original Data : 
 [[ 1.  2. nan  3.]
 [ 1.  2.  3. nan]
 [ 1.  2. nan  3.]
 [ 1.  2. nan  3.]]
modified_data using mean strategy : 
 [[1. 2. 3. 3.]
 [1. 2. 3. 3.]
 [1. 2. 3. 3.]
 [1. 2. 3. 3.]]
Origianl Data : 
 [[ 1.  2. nan]
 [ 3. nan  1.]
 [ 5. nan  0.]
 [nan  4.  6.]
 [ 5.  0. nan]
 [ 4.  5.  5.]]
modified_data using constant strategy :
 [[  1.   2. 100.]
 [  3. 100.   1.]
 [  5. 100.   0.]
 [100.   4.   6.]
 [  5.   0. 100.]
 [  4.   5.   5.]]


# Example 4: Missing Value Imputation

> **Objective:** Load the Breast Cancer dataset and replace missing (`NaN`) values with the **mean** using `SimpleImputer`.

<details>
<summary><strong>Task</strong></summary>

- Load the Breast Cancer dataset.
- Create a matrix containing missing (`NaN`) values.
- Use **SimpleImputer(strategy="mean")**.
- Replace missing values with the column mean.
- Display the original and updated matrix.

</details>

In [32]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.impute  import SimpleImputer
import numpy as np

Breastdata=load_breast_cancer()

x=Breastdata.data
y=Breastdata.target

x[0,0] = np.nan
x[5,2] = np.nan

# Cleaning Data

imp=SimpleImputer(missing_values=np.nan,strategy='mean')
modified_data=imp.fit_transform(x)

print("Modified  Data : ",modified_data[:10])
print("y Data : ",y[:10])



#

Modified  Data :  [[1.41e+01 1.04e+01 1.23e+02 1.00e+03 1.18e-01 2.78e-01 3.00e-01 1.47e-01
  2.42e-01 7.87e-02 1.09e+00 9.05e-01 8.59e+00 1.53e+02 6.40e-03 4.90e-02
  5.37e-02 1.59e-02 3.00e-02 6.19e-03 2.54e+01 1.73e+01 1.85e+02 2.02e+03
  1.62e-01 6.66e-01 7.12e-01 2.65e-01 4.60e-01 1.19e-01]
 [2.06e+01 1.78e+01 1.33e+02 1.33e+03 8.47e-02 7.86e-02 8.69e-02 7.02e-02
  1.81e-01 5.67e-02 5.43e-01 7.34e-01 3.40e+00 7.41e+01 5.22e-03 1.31e-02
  1.86e-02 1.34e-02 1.39e-02 3.53e-03 2.50e+01 2.34e+01 1.59e+02 1.96e+03
  1.24e-01 1.87e-01 2.42e-01 1.86e-01 2.75e-01 8.90e-02]
 [1.97e+01 2.12e+01 1.30e+02 1.20e+03 1.10e-01 1.60e-01 1.97e-01 1.28e-01
  2.07e-01 6.00e-02 7.46e-01 7.87e-01 4.58e+00 9.40e+01 6.15e-03 4.01e-02
  3.83e-02 2.06e-02 2.25e-02 4.57e-03 2.36e+01 2.55e+01 1.52e+02 1.71e+03
  1.44e-01 4.24e-01 4.50e-01 2.43e-01 3.61e-01 8.76e-02]
 [1.14e+01 2.04e+01 7.76e+01 3.86e+02 1.42e-01 2.84e-01 2.41e-01 1.05e-01
  2.60e-01 9.74e-02 4.96e-01 1.16e+00 3.44e+00 2.72e+01 9.11e-03 7.46e-